### ISSUE TITLE
kindly provide the reference paper for the same.

### ISSUE THREAD

**Issue by rajnigupta-555** [Shorya-Sharma/Game-Theory-For-Adversarial-Attacks-And-Defenses#1]
kindly provide the reference paper for the same.

**Comment by Shorya-Sharma** [comment]
I've provided the arxiv link for the paper under the 'about' section. You can check out the paper @ 'https://arxiv.org/abs/2110.06166v2'

**Comment by rajnigupta-555** [comment]
Thank you sir for your response, I will go through it and get back to you.

Thanks & Regards
